### ISSUE TITLE
non-support daily changes overlay is not listed

### ISSUE THREAD

**Issue by Sitoria** [darkchii/score-inspector-extension#11]
![image](https://github.com/user-attachments/assets/5c8cf992-bd9f-4ecf-953d-00079997adfd)
![image](https://github.com/user-attachments/assets/4012f8b3-2fa1-45ba-933c-c2dc4fff4986)
![image](https://github.com/user-attachments/assets/1fb2334e-7ec7-4060-ba03-16a5e4941f64)
![image](https://github.com/user-attachments/assets/e730be20-5073-4e4a-b51c-20ec1189cb5a)

🤷

**Comment by Sitoria** [comment]
![image](https://github.com/user-attachments/assets/325db669-6d41-457f-8420-44869dd55955)
if i reduce size:

**Comment by EngineerMark** [comment]
Saw u reported this 3h after i fixed it, make sure to be on 2024-07-25.35

8163e4147487a535254c61e4fb3a277d874a16aa
