### ISSUE TITLE
Global and Country SS ranking appear multiple times

### ISSUE THREAD

**Issue by MF-JEWM** [darkchii/score-inspector-extension#5]
![image](https://github.com/darkchii/score-inspector-extension/assets/120431769/3966249d-81d8-49b3-8ece-8e9492da4e21)

I disabled all my other userscripts and extensions. I noticed [here](https://github.com/darkchii/score-inspector-extension?tab=readme-ov-file#todo) it's noted that this feature was only added last week, so hopefully this helps to smooth out any bugs

**Comment by EngineerMark** [comment]
fixed in 23d67b9a6c0c7df6407bee36f2acd7a9739a3227 (2024-07-19.31)
