### ISSUE TITLE
Profiles are broken with new Daily Challenge stats

### ISSUE THREAD

**Issue by NoelleTGS** [darkchii/score-inspector-extension#8]
Daily Challenge statistics got deployed to osu-web a few hours ago, profiles are now a mess.

![image](https://github.com/user-attachments/assets/09b30d5a-e7bc-4ce2-9159-9bf1dc270748)

**Comment by NoelleTGS** [comment]
Oops, didn't see #7 before posting this.

**Comment by EngineerMark** [comment]
676ca3c165215014c2b5e6ea3b84cd4419db7d0c
